####
# This Dockerfile is used in order to build a container that runs the Spring Boot application
#
###
FROM registry.access.redhat.com/ubi9/openjdk-17:1.16 as JAR_EXTRACT
WORKDIR /app
ARG JAR_FILE=*.jar
COPY target/${JAR_FILE} ./app.jar
RUN java -Djarmode=layertools -jar ./app.jar extract


####
FROM registry.access.redhat.com/ubi9/openjdk-17:1.16
ARG APP_NAME=hello-spring-boot
ARG APP_VERSION=0.0.1-SNAPSHOT
ARG GIT_COMMIT_SHA
ARG GIT_COMMIT_BRANCH=develop

# Labels
LABEL maintainer="Red Hat Open Innovation Labs <open-innovation-labs@redhat.com>"
LABEL app-name="$APP_NAME"
LABEL app-version="$APP_VERSION"
LABEL git-commit-sha="$GIT_COMMIT_SHA"
LABEL git-commit-branch="$GIT_COMMIT_BRANCH"

# Working directory
WORKDIR /application

# Copy all dependencies
COPY --from=JAR_EXTRACT /app/dependencies ./
COPY --from=JAR_EXTRACT /app/spring-boot-loader ./
COPY --from=JAR_EXTRACT /app/snapshot-dependencies ./
COPY --from=JAR_EXTRACT /app/application ./

# Exposing port 8181
EXPOSE 8181

# Entrypoint
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.JarLauncher"]